#lang scheme
(define (make-segment start end)
  (make-point start end))
(define (start-segment seg)
  (x-point seg))
(define (end-segment seg)
  (y-point seg))
(define (make-point x y)
  (cons x y))
(define (x-point poi)
  (car poi))
(define (y-point poi)
  (cdr poi))
(define (average a b)
  (/ (+ a b) 2))
(define (midpoint-segment seg)
  (make-point (average (x-point (start-segment seg)) (x-point (end-segment seg))) (average (y-point (start-segment seg)) (y-point (end-segment seg)))))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ", ")
  (display (y-point p))
  (display ")"))
(define (make-rectangle segone segtwo)
  (make-point segone segtwo))
